server.port = 8085
server.servlet.context-path=/api/v1

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/security/protocol/openid-connect/certs

keycloak.host=http://localhost:8080
keycloak.login_api=/realms/security/protocol/openid-connect/token
keycloak.client_id=login
keycloak.client_secret=ycNhY1sahRYwbvBx2CpzpPCZTc9e1UVa
